import { useMemo, useState } from "react"
import { Link, useParams } from "react-router-dom"
import { AlertCircle, Download, FileText, Loader2 } from "lucide-react"
import { PageHeader } from "@/components/common/PageHeader"
import { EmptyState } from "@/components/common/EmptyState"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import { useReportsQuery } from "@/hooks/useReports"
import { downloadEvidenceReport } from "@/api/reports.api"
import { getErrorMessage } from "@/api/client"
import { formatDateTime } from "@/lib/utils"
import type { ReportListItem } from "@/api/reports.api"

function availableFormats(report: ReportListItem): Array<"json" | "pdf"> {
  const formats: Array<"json" | "pdf"> = []
  if (report.has_json) formats.push("json")
  if (report.has_pdf) formats.push("pdf")
  return formats
}

export default function ReportsPage() {
  const { caseId } = useParams<{ caseId?: string }>()
  const { data, isLoading, isError, error, refetch, isFetching } = useReportsQuery()
  const [downloadingId, setDownloadingId] = useState<string | null>(null)
  const [downloadError, setDownloadError] = useState<string | null>(null)
  const reports = useMemo(() => {
    const rows = data ?? []
    if (!caseId) return rows
    return rows.filter((report) => report.case === caseId)
  }, [data, caseId])

  const handleDownload = async (
    report: ReportListItem,
    format: "json" | "pdf"
  ) => {
    setDownloadError(null)
    setDownloadingId(`${report.id}:${format}`)
    try {
      const blob = await downloadEvidenceReport(report.id, format)
      const url = URL.createObjectURL(blob)
      const anchor = document.createElement("a")
      const safeName =
        report.report_id.replace(/[^\w.-]+/g, "_") || `report-${report.id}`
      anchor.href = url
      anchor.download = `${safeName}.${format}`
      document.body.appendChild(anchor)
      anchor.click()
      anchor.remove()
      URL.revokeObjectURL(url)
    } catch (err) {
      setDownloadError(getErrorMessage(err))
    } finally {
      setDownloadingId(null)
    }
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Generated forensic reports for cases you can access. Opening this page is read-only — generate reports from an evidence detail page."
        actions={
          <Button asChild variant="secondary" className="gap-2">
            <Link to="/cases">
              <FileText className="h-4 w-4" />
              Open a case to generate
            </Link>
          </Button>
        }
      />

      {downloadError ? (
        <p className="text-sm text-danger" role="alert">
          {downloadError}
        </p>
      ) : null}

      {isLoading ? (
        <div className="flex min-h-[30vh] items-center justify-center gap-2 text-sm text-text-muted">
          <Loader2 className="h-4 w-4 animate-spin" />
          Loading reports…
        </div>
      ) : null}

      {isError ? (
        <EmptyState
          icon={<AlertCircle className="h-6 w-6 text-danger" />}
          title="Could not load reports"
          description={getErrorMessage(error)}
          action={
            <Button
              variant="secondary"
              onClick={() => void refetch()}
              disabled={isFetching}
            >
              Try again
            </Button>
          }
        />
      ) : null}

      {!isLoading && !isError && reports.length === 0 ? (
        <EmptyState
          icon={<FileText className="h-6 w-6" />}
          title="No reports have been generated yet."
          description="Reports are created only when you explicitly generate them from an evidence detail page. Opening this page does not create report files."
          action={
            <Button asChild variant="secondary">
              <Link to="/cases">Browse cases</Link>
            </Button>
          }
        />
      ) : null}

      {!isLoading && !isError && reports.length > 0 ? (
        <Card>
          <CardContent className="p-0">
            <div className="overflow-x-auto">
              <table className="w-full min-w-[880px]">
                <thead>
                  <tr className="border-b border-white/[0.06] text-left text-xs uppercase tracking-wider text-text-muted">
                    <th className="px-4 py-3 font-medium">Report ID</th>
                    <th className="px-4 py-3 font-medium">Evidence / Case</th>
                    <th className="px-4 py-3 font-medium">Format</th>
                    <th className="px-4 py-3 font-medium">Generated</th>
                    <th className="px-4 py-3 font-medium">Generated by</th>
                    <th className="px-4 py-3 font-medium">Available</th>
                    <th className="px-4 py-3 font-medium">Download</th>
                  </tr>
                </thead>
                <tbody>
                  {reports.map((report) => {
                    const formats = availableFormats(report)
                    return (
                      <tr
                        key={report.id}
                        className="border-b border-white/[0.04] align-top hover:bg-white/[0.02]"
                      >
                        <td className="px-4 py-4">
                          <p className="break-all font-mono text-xs text-accent">
                            {report.report_id}
                          </p>
                          {report.title ? (
                            <p className="mt-1 break-words text-sm text-white">
                              {report.title}
                            </p>
                          ) : null}
                        </td>
                        <td className="px-4 py-4 text-sm">
                          <p className="break-words text-white">
                            {report.evidence_filename || "Evidence"}
                          </p>
                          <p className="mt-1 break-words text-xs text-text-muted">
                            {report.case_title || report.case}
                          </p>
                          {report.evidence ? (
                            <Link
                              to={`/evidence/${report.evidence}`}
                              className="mt-1 inline-block text-xs text-accent hover:underline"
                            >
                              Open evidence
                            </Link>
                          ) : null}
                        </td>
                        <td className="px-4 py-4">
                          <Badge variant="secondary">
                            {report.report_type || "json"}
                          </Badge>
                        </td>
                        <td className="px-4 py-4 text-sm text-text-secondary">
                          {report.created_at
                            ? formatDateTime(report.created_at)
                            : "—"}
                        </td>
                        <td className="px-4 py-4 text-sm text-text-secondary">
                          {report.generated_by_username ||
                            report.generated_by ||
                            "—"}
                        </td>
                        <td className="px-4 py-4">
                          <div className="flex flex-wrap gap-1">
                            {formats.length === 0 ? (
                              <span className="text-xs text-text-muted">
                                Unavailable
                              </span>
                            ) : (
                              formats.map((fmt) => (
                                <Badge key={fmt} variant="secondary">
                                  {fmt.toUpperCase()}
                                </Badge>
                              ))
                            )}
                          </div>
                        </td>
                        <td className="px-4 py-4">
                          <div className="flex flex-wrap gap-2">
                            {formats.map((fmt) => {
                              const busyKey = `${report.id}:${fmt}`
                              const pending = downloadingId === busyKey
                              return (
                                <Button
                                  key={fmt}
                                  size="sm"
                                  variant="secondary"
                                  className="gap-1.5"
                                  disabled={Boolean(downloadingId)}
                                  onClick={() => void handleDownload(report, fmt)}
                                >
                                  {pending ? (
                                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                                  ) : (
                                    <Download className="h-3.5 w-3.5" />
                                  )}
                                  {fmt.toUpperCase()}
                                </Button>
                              )
                            })}
                          </div>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      ) : null}

      <p className="text-xs text-text-muted">
        Download uses the authenticated report endpoint. Each successful download
        may record an evidence_exported custody event per existing platform
        behavior.
      </p>
    </div>
  )
}
