# Generated by Django 5.2.17 on 2026-09-21 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=512)),
                ('storage_name', models.CharField(max_length=128, unique=True)),
                ('stored_path', models.CharField(max_length=1024)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(blank=True, default='', max_length=128)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('md5', models.CharField(blank=True, default='', max_length=32)),
                ('sha1', models.CharField(blank=True, default='', max_length=40)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acquisition_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='cases.case')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyEventRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('action', models.CharField(max_length=64)),
                ('actor_id', models.CharField(blank=True, default='', max_length=128)),
                ('actor_role', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, default='django', max_length=64)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
                ('evidence_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('previous_event_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('event_hash', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='cases.case')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='evidence.evidence')),
            ],
            options={
                'ordering': ['timestamp', 'created_at'],
                'indexes': [models.Index(fields=['evidence', 'timestamp'], name='evidence_cu_evidenc_c48d01_idx')],
            },
        ),
    ]
