# Generated by Django 5.2.17 on 2026-09-21 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('metadata', 'Metadata'), ('keyword', 'Keyword'), ('browser', 'Browser'), ('timeline', 'Timeline'), ('report', 'Report'), ('ai', 'AI')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='cases.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='evidence.evidence')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['evidence', 'analysis_type', 'status'], name='evidence_an_evidenc_d33d3b_idx'), models.Index(fields=['evidence', '-created_at'], name='evidence_an_evidenc_15410d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.CharField(max_length=64, unique=True)),
                ('report_type', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('both', 'Both')], default='json', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('json_path', models.CharField(blank=True, default='', max_length=1024)),
                ('pdf_path', models.CharField(blank=True, default='', max_length=1024)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cases.case')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='evidence.evidence')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', '-created_at'], name='evidence_re_case_id_42d5cf_idx'), models.Index(fields=['evidence', '-created_at'], name='evidence_re_evidenc_74d983_idx')],
            },
        ),
    ]
