# Generated by Django 5.2.17 on 2026-08-08 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigated_cases', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='case_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=512)),
                ('storage_name', models.CharField(max_length=128, unique=True)),
                ('stored_path', models.CharField(max_length=1024)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(blank=True, default='', max_length=128)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('md5', models.CharField(blank=True, default='', max_length=32)),
                ('sha1', models.CharField(blank=True, default='', max_length=40)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acquisition_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='investigations.case')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('hash', 'Hash'), ('metadata', 'Metadata'), ('keyword', 'Keyword'), ('browser', 'Browser'), ('timeline', 'Timeline'), ('custody', 'Custody'), ('report', 'Report'), ('ai', 'AI')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='investigations.case')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='investigations.evidence')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.CharField(max_length=64, unique=True)),
                ('report_type', models.CharField(default='json', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('json_path', models.CharField(blank=True, default='', max_length=1024)),
                ('pdf_path', models.CharField(blank=True, default='', max_length=1024)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='investigations.case')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='investigations.evidence')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyEventRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('action', models.CharField(max_length=64)),
                ('actor_id', models.CharField(blank=True, default='', max_length=128)),
                ('actor_role', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, default='django', max_length=64)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
                ('evidence_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('previous_event_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('event_hash', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='investigations.case')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='investigations.evidence')),
            ],
            options={
                'ordering': ['timestamp', 'created_at'],
                'indexes': [models.Index(fields=['evidence', 'timestamp'], name='investigati_evidenc_4f3e84_idx')],
            },
        ),
    ]
